name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: asdf-vm/actions/plugin-test@v3
        with:
          command: tkn-pac version